### ISSUE TITLE
Probenwerte (PW) der Fertigkeiten wurden nicht halbiert

### ISSUE THREAD

**Issue by KaiderWeise** [Plushtoast/dsk-foundryVTT#14]
Um an den Probenwert zu gelangen werden die beiden beteiligten Eigenschaften addiert, dann halbiert (aufgerundet) = Eigenschaftswert
Dann wird auf den Eigenschaftswert der FW addiert und 5 hinzugezählt = PW

-> Die Halbierung der Summe der beiden Eigenschaften erfolgt nicht und die PW ist folglich zu hoch.

**Comment by Plushtoast** [comment]
halbierung dezent überlesen
