### ISSUE TITLE
Kleine erste Fehlersammlung

### ISSUE THREAD

**Issue by KaiderWeise** [Plushtoast/dsk-foundryVTT#15]
Eine kurze Aufstellung der ersten aufgefallenen Punkte:

- [x] Unter Gesellschaftsfertigkeiten fehlt die Fertigkeit Willenskraft
- [x] Die Sonderfertigkeit "Allsprache" ist nicht als "Sprache" kategorisiert, sondern als "Allgemein"
- [x]  Eigens angelegte Waffen erhalten kein automatisches Icon, wie z.B. die Vorteile, Nachteile und SF
- [x] Eigens angelegte Rüstungen erhalten kein automatisches Icon, wie z.B. die Vorteile, Nachteile und SF.
- [x] Eigens angelegte Ahnengaben erhalten kein automatisches Icon, wie z.B. die Vorteile, Nachteile und SF.
- [x]  Der Charakterbogen oben ist abgeschnitten und der Name nicht erkennbar.
- [x] ![DSK Charakterbogen oben abgeschnitten](https://user-images.githubusercontent.com/78543670/202820848-a50e5185-c6cd-439a-9e47-2b23aaa3e721.JPG)

**Comment by Plushtoast** [comment]
layout kommt zum schluss, die grafiken existieren noch nicht.
danke!

**Comment by KaiderWeise** [comment]
Ja, waren die ersten Dinge. Und zumindest die ersten beiden Punkte, insbesondere die fehlende Fertigkeit sind ja schon wat anderes :)
