### ISSUE TITLE
Fehler im dsk.ActorSheetCreature und im dsk.ActorSheetCharacter

### ISSUE THREAD

**Issue by KaiderWeise** [Plushtoast/dsk-foundryVTT#17]
DSK 0.0.3

**dsk.ActorSheetCreature**

1. In den Feldern "Beschreibung", "Kampfverhalten" und "Sonderregeln" werden geschriebene Texte zwar gespeichert, aber nicht angezeigt. 
Im Feld "Private Notizen" ist dies jedoch alles gut. Der Text wird auch angezeigt. 
![Notizen Felder](https://user-images.githubusercontent.com/78543670/202867179-92b58010-c291-4236-be9e-c80ac6494747.JPG)
![Notizen Felder gespeichert](https://user-images.githubusercontent.com/78543670/202867181-01215b90-5d0a-4467-ab39-56cd2b678f45.JPG)

2. Statt Typus steht auf dem Bogen "Rasse" und müsst geändert werden
![Rasse](https://user-images.githubusercontent.com/78543670/202871805-4637f27b-909b-48ba-b4e0-c6744248d17f.JPG)

3. Lebensenergie kann nicht als Wert eingegeben werden. Lediglich die Möglichkeit über den "Mod." zu gehen besteht.
![Lebensnenergie](https://user-images.githubusercontent.com/78543670/202871868-813bfd52-a428-4f0f-acda-5c88aa8c564c.JPG)

4. Die Anordnung der Eigenschaften ist durcheinander. Richtige Reihenfolge ist -> MU KL IN CH FF GE KO KK
Zumindest ist dies in dieser Reihenfolge in den Werteblöcken der NSC so aufgeführt.
![Eigenschaften](https://user-images.githubusercontent.com/78543670/202872132-7f778ebd-7e44-41ed-9fae-7d30019eef0a.JPG)

**dsk.ActorSheetCharacter**

1. Es scheint bei der Belastung etwas nicht zu stimmen. Ich habe die Belastung manuell als Status auf 2 gesetzt (weil die Katze eine Kettenrüstung trägt mit RS4 / BE 4 aber über Belastungsgewöhnung II verfügt). Im Ausrüstungs-Tab wird dies als -1 angezeigt und bei der Probe (hier Körperbeherrschung) natürlich nicht berücksichtigt.

![Belastung manuell](https://user-images.githubusercontent.com/78543670/202875276-8eda843c-0dbf-4090-8c40-4533d92a4f58.JPG)
![Belastung unter Ausrüstung](https://user-images.githubusercontent.com/78543670/202875279-cbbeda6e-aad7-4f72-a27a-e15795ed3b54.JPG)
![Belastung keine Anwendung bei Probe](https://user-images.githubusercontent.com/78543670/202875282-e39d18c6-b209-40c6-8c9c-bad5e6704433.JPG)

**Comment by Plushtoast** [comment]
Status Effekte gehen noch nicht. Die bekommmen eine signifikante Änderung im Vergleich zu DSA. Diese Änderung wird dann auch nach DSA noch wandern

**Comment by Plushtoast** [comment]
Status siehe Auflösung von #7
