### ISSUE TITLE
dsk.ActorSheetCreature: Kopfnuss, Haltegriff und Ohrbiss werden automatisch zugewiesen

### ISSUE THREAD

**Issue by KaiderWeise** [Plushtoast/dsk-foundryVTT#18]
DSK 0.0.4

Die Sonderfertigkeiten Kopfnuss, Haltegriff und Ohrbiss werden aktuell Kreaturen standardmäßig zugewiesen. Diese SF stehen aber laut Regeltext/Beschreibung nur automatisch Katzenhelden zu. Kreaturen erhalten diese nicht automatisch.

**Comment by Plushtoast** [comment]
Keine ahnung was hunde und co später haben, aber vlt wird das hier noch irgendwie an die spezies geknüpft
