### ISSUE TITLE
Raufen als Standard VW

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsk-foundryVTT#20]
Sobald keine Waffe aktiv ausgerüstet ist, oder die aktiv ausgerüsteten Waffen über keinen VW verfügen (Fernkampf), sollte der Raufen VW verwendet werden.

**Comment by Plushtoast** [comment]
Es wird inzwischen automatisch eine Waffe "Raufen" dem bogen hinzugefügt die genau das tut

**Comment by vt-tom** [comment]
In Version 0.4 hat er das bei einem neuen Actor noch nicht gemacht.

**Comment by KaiderWeise** [comment]
Kann ich bestätigen. Raufen wird nicht automatisch als Waffe hinzugefügt in 0.4
