### ISSUE TITLE
[Idee] Tooltip auf dem Fertigkeitsbogen beim Probenwert

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsk-foundryVTT#21]
Damit nachvollzogen werden kann wie sich der Probenwert erreichnet, wäre es hilfreich auf dem Fertigkeiten Bogen einen Tooltip über dem PW zu haben der angibt aus welchen Werten sich dieser errechnet.

**Comment by Plushtoast** [comment]
Ich denke um einmal die regeln lesen kommt der gamemaster nicht rum und die formel ist für alle würfe gleich und auch nicht so besonders

**Comment by vt-tom** [comment]
Ging mir nur um die Idee, Einsteiger Spielern das System damit ggf nochmal näher bringen zu können. Ist aber absolut nicht notwendig, da hast du recht.
Als GM sollte man tatsächlich wissen woher die Werte kommen.
