### ISSUE TITLE
Fehler beim Klick auf Effekte in Tokenhotbar

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsk-foundryVTT#24]
Beim Klick auf den Effekte Button in der Token hotbar kommt es zu einer Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/80099175/203907984-f0c3653f-8bc5-46b2-a0a3-3c8bdabab82f.png)

![grafik](https://user-images.githubusercontent.com/80099175/203907964-e74b37c9-991e-4d4c-8fef-eac0b6378327.png)

**Comment by Plushtoast** [comment]
b taste geht im nächsten patch
bild hier auf die liste gesetzt: #2
