### ISSUE TITLE
Kampftracker: Icon fehlt und B Taste hinzufügen

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsk-foundryVTT#26]
Ist ein Kampf aktiv, wird das Symbol im Kampf tracker noch nicht richtig dargestellt. Außerdem wäre es hiflreich wenn die B Taste als Shortcut auch hier funktioniert.

![grafik](https://user-images.githubusercontent.com/80099175/203921225-4b2116c3-a6f8-452a-a67e-ec1a36e2aa33.png)

**Comment by Plushtoast** [comment]
b taste geht im nächsten patch
bild hier auf die liste gesetzt: #2
