### ISSUE TITLE
Belastung von Rüstungen funktioniert noch nicht

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsk-foundryVTT#35]
Wird eine Rüstung mit einer Belastung angelegt, wird dies nicht auf den Akteur angewendet.

**Comment by Plushtoast** [comment]
Das geht bei mir

**Comment by vt-tom** [comment]
Also ich habe hier eine Belastung von 4 und sie wird bei den Proben nicht angewendet:
![grafik](https://user-images.githubusercontent.com/80099175/204356743-084a6a49-22ac-4085-b15c-aae71d7896a5.png)
![grafik](https://user-images.githubusercontent.com/80099175/204356820-cf54d5df-855f-475d-9639-874f732d2d28.png)

**Comment by Plushtoast** [comment]
![grafik](https://user-images.githubusercontent.com/44941845/204359355-16c5fd72-4914-4178-b68b-e84aa4d1660a.png)
