### ISSUE TITLE
Meldung beim Starten einer neuen Welt mit generic value

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsk-foundryVTT#36]
Wird eine neue Welt gestartet und der Sprachdialog erscheint, ist dieser noch als generic value hinterlegt.
![grafik](https://user-images.githubusercontent.com/80099175/204281834-1e9db8bf-858e-46c9-8243-8f4fb3297649.png)

**Comment by Plushtoast** [comment]
das geht bei mir
irgendein modul aktiv gewesen?

**Comment by Plushtoast** [comment]
ah ne das ist weil du mit englisch einsteigst hm

**Comment by vt-tom** [comment]
Jo, habe das Modul German (Core) nicht installiert.
