### ISSUE TITLE
Angriffstreffer - keine Erfolgsmeldung und kein Schaden

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsk-foundryVTT#37]
Trifft ein Angriff, gibt es im Chat keine Erfolgsmeldung und keine Schadensnachricht:
![grafik](https://user-images.githubusercontent.com/80099175/204854144-144ba90d-9220-472b-84d1-4856aaae15cd.png)

**Comment by Plushtoast** [comment]
Die wirds erst im Januar geben
