### ISSUE TITLE
Links und Bilder in classes sind nicht klickbar

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsk-foundryVTT#42]
Wird ein Link oder ein Bild in einem Block mit Class platziert, ist dieser nicht klickbar. 
Bei Links ist dies nur im Journalbrowser so, bei Bilder klappt es sowohl im Journal Browser als auch im Journal selbst nicht.

Könnte aber auch ein Foundry Problem sein.

![grafik](https://user-images.githubusercontent.com/80099175/204991539-945fa30a-72d0-464f-9a15-780d47a234c8.png)

**Comment by Plushtoast** [comment]
sollte im nächsten patch passen, falls nicht nochmal sagen bitte
