### ISSUE TITLE
[Feature] Ahnengaben um Aktionsdauer erweitern

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsk-foundryVTT#53]
Alle Ahnengaben brauchen 2 Aktionen. Hilfreich wäre es, wenn dies auch bei den Ahnengaben sichtbar wäre. Spätestens wenn im Kampf das Tracking dieser Dauer hinzukommt.

Verweiß auf Regeln:
Seite 167 alle Ahnengaben benötigen 2 Aktionen: Ahnengabe: Ahnengaben erzeugen übernatürli-
che Effekte. Sie sind für Ahnenkinder erlernbar 
wie Fertigkeiten und erfordern zum Wirken zwei 
Aktionen. Sie sind damit länger dauernde Hand-
lungen (siehe Seite 148)

**Comment by Plushtoast** [comment]
Was genau meinst du?
Hier stehts:
![grafik](https://user-images.githubusercontent.com/44941845/208236235-e5578629-cd0e-46a7-8e04-49f7c14bf8c3.png)


Und im chat auch:
![grafik](https://user-images.githubusercontent.com/44941845/208236253-42bb257c-1172-4d6a-a85a-01540fd8c387.png)
