### ISSUE TITLE
Belastung hat keine Auswirkung auf Werte

### ISSUE THREAD

**Issue by ZeroIchiro** [Plushtoast/dsk-foundryVTT#66]
Laut Seite 68 des GRW: "Pro Stufe erhält der Charakter eine Erschwernis von -1 auf Fertigkeiten, die durch Belastung erschwert
werden."
Das ist aber im FVTT-Modul noch nicht berüskcsichtigt. Legt man ein Item an, bspw. die Lederrüstung, und gibt ihr eine Belastung von 3, werden diese 3 nicht von den FW der Fertigkeiten abgezogen, auch wenn diese ausgerüstet ist.
Laut Issue-History soll das gefixed sein, aber ich kann das nicht bestätigen:
![grafik](https://user-images.githubusercontent.com/51971338/219053561-5b13051f-1fa9-4348-9d4a-8cf0da9e064c.png)
(BE 1 wegen "Belastungsgewöhnung Stufe II")
![grafik](https://user-images.githubusercontent.com/51971338/219053697-6d3a60b2-40fb-4cec-bf7a-ec4900e47f9a.png)

Aber:

![grafik](https://user-images.githubusercontent.com/51971338/219053811-07dec5bf-dee0-4f9c-9cc7-d2782f9609bd.png)

Friemeln dürfte laut meiner Rechnung nur 23 sein, nicht 24 (GE = 14, FF = 12, ergibt 13+FW 6 = 19 +5 = 24, -1 BE = 23)

**Comment by Plushtoast** [comment]
Zustände werden erst am roll dialog angezeigt. Sie sind nicht immer gültig und deswegen situationsbedingte modifikatoren. man kann sie bei jedem wurf an oder abwählen, sofern notwendig.

![grafik](https://user-images.githubusercontent.com/44941845/220701586-a498f314-404c-4353-88dc-a2a8048190d5.png)
