### ISSUE TITLE
Kampf funktioniert nicht

### ISSUE THREAD

**Issue by Wanderkater** [Plushtoast/dsk-foundryVTT#74]
Das Spiel wurde gestartet, 2 Token auf der Map (die dazugehörigen Akteure sind auch Importiert), Ini gewürfelt, Begegnung gestartet, Token stehen nebeneinander.
Dann wähle ich über die Inileiste auf das Schwertsymbol und wähle die Angriffsaktion. Danach geschieht nichts mehr. Kein Würfeln usw. Das Würfelfeld steht weiterhin offen.
Auch ein Würfeln über die Kampfschaltfläche im Charakterbogen geht nicht. Fertigkeitenproben gehen jedoch problemlos.
So sieht die Oberfläche dabei aus
![Fehlercode Foundary_2](https://github.com/Plushtoast/dsk-foundryVTT/assets/81418376/00ca14ee-d119-42cb-b1ab-81f5d55d88a6)

Der Fehlercode selbst sieht so aus:
![Fehlercode Foundary](https://github.com/Plushtoast/dsk-foundryVTT/assets/81418376/292e5704-f9d8-449f-a634-fa4da7886859)

**Comment by Plushtoast** [comment]
Kannst du mal in der Konsole weiter hoch scrollen, ob da davor noch ein anderer Fehler kommt?

**Comment by Wanderkater** [comment]
Davor kommt kein weiterer Fehler.

**Comment by Plushtoast** [comment]
Bitte einmal in der Konsole folgendes eingeben

```js
game.dsk.apps.CreatureType.creatureData
```

danach 
```
game.i18n.lang
```
und ergebnis hier postne

**Comment by Wanderkater** [comment]
![Fehlercode Foundary_3](https://github.com/Plushtoast/dsk-foundryVTT/assets/81418376/fecbca5e-f025-4368-9558-c3f5a598bd22)
