### ISSUE TITLE
Anzahl Schips zu hoch

### ISSUE THREAD

**Issue by Brausepaul** [Plushtoast/dsk-foundryVTT#77]
Ich habe festgestellt, dass ein (unter 2.0 angelegter) Charakter (Barde, Scheunenkatze) mit Glück I insgesamt 5 mögliche Schicksalspunkte hat. Erwarten würde ich vier. Ich habe keinen Modifikator im Charakterbogen eingefügt. Nach dem Entfernen von Glück I verbleiben vier Schicksalspunkte. Aufgefallen ist das Problem unter 2.1, es besteht unter 2.1.2 auch noch.

![anonym](https://github.com/Plushtoast/dsk-foundryVTT/assets/13948653/31cf670c-8e57-41f6-8413-b86caeb493bf)
[fvtt-Actor-streng-geheim-t8b6BFRUHkFthXbN.zip](https://github.com/Plushtoast/dsk-foundryVTT/files/12572845/fvtt-Actor-streng-geheim-t8b6BFRUHkFthXbN.zip)

**Comment by vt-tom** [comment]
Da war unter Status noch ein alter Effekt. Den habe ich zusammen mit dem Vorteil entfernt und dann den Vorteil neu in den Char gezogen. Jetzt passsen die Schips wieder. Entweder genauso nachmachen oder die hier anhängende Json importieren:  
[fvtt-Actor-strenggeheim-lbC5nAHZ78KDjCDT.zip](https://github.com/Plushtoast/dsk-foundryVTT/files/12573413/fvtt-Actor-strenggeheim-lbC5nAHZ78KDjCDT.zip)

@Plushtoast kann geschlossen werden.

**Comment by Brausepaul** [comment]
Herzlichen Dank. Hat - wie beschrieben - funktioniert.
