### ISSUE TITLE
Probleme mit Zuständen und Effektkontainern

### ISSUE THREAD

**Issue by Swarsulf** [Plushtoast/dsk-foundryVTT#82]
Hallöchen, ich bin gerade dabei, Donnerbach mit in Foundry zu Implementieren (für Private Nutzung) und habe folgendes Problem:

Wenn ich bei Gegenständen, Sonderfertigkeiten, Vorteile/Nachteile etc. einen Zustand hinzufügen will, Funktioniert dieses nicht.
![Unbenannt](https://github.com/user-attachments/assets/d02d66b1-ff4b-40cb-a411-44dc26397fe8)
Es erscheint nur das Info-Fenster "Zustand hinzufügen", aber mehr auch nicht.

Bin auf Foundry Version 12 Stable, Build 329.
DSK-Version 3.0.4. mit dem Grundregelwerk, Bestiarium, Einsteigerbox und Fasar - Brüchiger Frieden

**Comment by Plushtoast** [comment]
Kann ich nicht nahcvollziehen. Geht bei mir einwandfrei. Kannst du mal mit F12 die Konsole öffnen und alle Fehler (rot) die du siehst hier posten?

**Comment by Swarsulf** [comment]
Es werden mir keine Fehler angezeigt..
Hab mal ein Video von gemach:
https://www.dropbox.com/scl/fi/nvmxv1salt2uixyva3mkn/Desktop-2024.07.21-17.15.20.01.mp4?rlkey=a9cvjfjeweaod88jt5de0rn84&st=o10jxoik&dl=0

**Comment by Plushtoast** [comment]
Ach du machst das in einem Kompendium. Das ist aktuell geblockt.
Es sollte funktionieren wenn du den Effekt in der Welt anlegst und danach ins Kompendium schiebst.

**Comment by Swarsulf** [comment]
Ich habe es nun gemacht, wie du vorgeschlagen hast, bin aber auf ein weiteres Problem gestoßen:
Versuche ich einen zweiten Attributsschlüssel im selben Effekt zu erstellen, bekomm ich den folgenden Fehler.
![Unbenannt](https://github.com/user-attachments/assets/1095afa1-43a0-407d-abe9-9a4fe0dc531c)
