### ISSUE TITLE
Abzug der AeP und weitere Probleme

### ISSUE THREAD

**Issue by Mondroete** [Plushtoast/dsk-foundryVTT#85]
Problem 1:
In der Version: Foundry 12.331 / DSK 3.0.7 funktioniert der AeP Abzug über Chat nicht mehr.
![image](https://github.com/user-attachments/assets/e06509cf-4535-4bb3-94a8-7424f0583257)

Problem 2
Wenn man bei Zaubern zum Beispiel die Formal 2d6+(QS*3) bei Effekt eingibt, erscheint kein Wurf mehr im Chat. Gewürfelt wird aber.
![image](https://github.com/user-attachments/assets/c03aa755-d54a-4ceb-b6b7-2c3623caf86e)

Problem 3
Hinterlegte Effekte (z.B. Furcht) können nicht über den Chat aktiviert werden.
-> Hat ein Gegenstand, oder eine Ahnenfähigkeit ein Effekt, funktioniert es nicht diesen nach dem Würfeln über den Chat Effekt (Selbst) oder Effekt (Ziel) anzuwenden. Hier Passiert einfach nichts. 
![image](https://github.com/user-attachments/assets/fd80dd45-30d5-4dd8-97dc-29cbf7dfbceb)

Problem 4
Kampfreflexe effekt nicht aktiv wird, hier muss ebenfalls Manuel nach geholfen werden. (hat jemand anderes fest gestellt)

Problem 5
Hat ein Akteur ein Gegenstand, auf den man einen Effekt setzen will, geht dies nicht im Charakter Cheat, man muss es immer als Item so erstellen und dann wieder auf den Akteur ziehen um es dann zu testen.
Haben die Gegenstände einen Effekt kann man ihn beliebig bearbeiten, aber sollte er sich Deaktivieren bekommt man ihn nicht aktiv.
![image](https://github.com/user-attachments/assets/91c858cc-4b4b-46dc-92c1-d67fd5747933)

----------------------------------------------------------------------------------------------------------------

Frage:
Ist es Möglich bei den Verbrauchsgegenständen die Ausrüsstungskategorie selbst zu beschriften um die Gegenstände vom Papierschnüffler und Akâmandra-Schnitzer anzulegen? Beides kam mit Donnerbach dazu. 
Buch: Schleichender Verfall ab S.155

---------------------------------------------------------------------------------------------------------------

Das wichtigste an dem ganzen ist aber Problem 1 ^^°

tut mir leid für diese lange Liste.

**Comment by Plushtoast** [comment]
Features aus Büchern die noch nicht als offizielles Modul existieren sind leider nicht möglich. Unter anderem weil ich die PDFs auch gar nicht habe.

**Comment by Mondroete** [comment]
Verstehe :)

jedenfalls danke für die Mühe, es geht alles ohne Probleme
Der Schaden von den Zaubern muss zwar Manuell abgezogen werden, aber das ist kein Beinbruch :).

Vielen Dank für die Arbeit.
